### ISSUE TITLE
CRS checks only check for one specific format (candex_calss_march branch)

### ISSUE THREAD

**Issue by wknoben** [ShervanGharari/candex_newgen#2]
Example 1 currently stops on:
```
cndx.run_candex()
```
`An exception has occurred, use %tb to see the full traceback.`
`SystemExit: please project your shapefile to WGS84 (epsg:4326)`

while the CRS is set correctly: 
```
shp = gpd.read_file(cndx.sink_shp)
shp.crs
```
`{'init': 'epsg:4326'}`

This can be traced to the checks used in `check_target_shp()` (lines 195-198):
```
if (str(shp.crs).lower() != 'epsg:4326'):
            sys.exit('please project your shapefile to WGS84 (epsg:4326)')
        if (str(shp.crs).lower() == 'epsg:4326'): # check if the projection is WGS84 (or epsg:4326)
            print('candex detects that target shapefile is in WGS84 (epsg:4326)')
```

`check_source_nc_shp()` (lines 350-353):
```
if (str(shp.crs).lower() != 'epsg:4326'):
            sys.exit('please project your source shapefile and varibales in source nc files to WGS84 (epsg:4326)')
        if (str(shp.crs).lower() == 'epsg:4326'): # check if the projection is WGS84 (or epsg:4326)
            print('candex detects that source shapefile is in WGS84 (epsg:4326)')
```

and `run_candex()` (line 106):
```
if (str(shp_1.crs).lower() == str(shp_2.crs).lower()) and (str(shp_1.crs).lower() == 'epsg:4326'):
```

**Comment by ShervanGharari** [comment]
ok the is what it returns for me
```
import geopandas as gpd
shp = gpd.read_file(cndx.sink_shp)
print(shp.crs)
```
epsg:4326

I will into this...

**Comment by ShervanGharari** [comment]
Is this related to this problem?

https://geopandas.org/docs/user_guide/projections.html

Manually specifying the CRS

When specifying the CRS manually in your code (e.g., because your data has not yet a CRS, or when converting to another CRS), this might require a change in your code.

“init” proj4 strings/dicts

Currently, a lot of people (and also the GeoPandas docs showed that before) specify the EPSG code using the “init” proj4 string:

## OLD
GeoDataFrame(..., crs={'init': 'epsg:4326'})
# or
gdf.crs = {'init': 'epsg:4326'}
# or
gdf.to_crs({'init': 'epsg:4326'})
The above will now raise a deprecation warning from pyproj, and instead of the “init” proj4 string, you should use only the EPSG code itself as follows:

## NEW
GeoDataFrame(..., crs="EPSG:4326")
# or
gdf.crs = "EPSG:4326"
# or
gdf.to_crs("EPSG:4326")

**Comment by wknoben** [comment]
Yes, that is the problem I think. I think it is straightforward to adapt the checks to account for both old and new cases:

```
if 'epsg:4326' not in str(shp.crs).lower():
    print('not epsg:4326')
else:
    print('candex detects that target shapefile is in WGS84 (epsg:4326)')
```
This checks if `EPSG:4326` occurs in the CRS but does not look for an exact match. As long as this string is in the longer string, it'll return `True`.

**Comment by ShervanGharari** [comment]
here is my specification for geopandas and pyproj
```
geopandas                          0.8.1
pyproj                             3.0.0.post1
```
yours?

**Comment by ShervanGharari** [comment]
I see, I will change this of course...

**Comment by wknoben** [comment]
```
geopandas    0.6.1
pyproj            2.6.1.post 1
```
Seems possibly that this is a version issue with old/new formats based on this.

**Comment by ShervanGharari** [comment]
I see so yours is the old one but I will fix it as you mentioned so that it can work with older geopdans as well

**Comment by ShervanGharari** [comment]
changed, please check and see if it works. then I close the issue.

**Comment by wknoben** [comment]
I've updated my local copy of the code and it does not show this error anymore

**Comment by ShervanGharari** [comment]
excellent! issue closed!
